"""initial migration

Revision ID: 8ad6062f61ef
Revises: 
Create Date: 2025-05-15 14:24:57.982441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ad6062f61ef'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creditor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cpf_cnpj', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf_cnpj')
    )
    op.create_table('precatory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credor_id', sa.Integer(), nullable=False),
    sa.Column('numero_precatorio', sa.String(), nullable=False),
    sa.Column('valor_nominal', sa.Float(), nullable=False),
    sa.Column('foro', sa.String(), nullable=True),
    sa.Column('data_publicacao', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['credor_id'], ['creditor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('precatory')
    op.drop_table('creditor')
    # ### end Alembic commands ###
