"""att table users

Revision ID: b3146cc95350
Revises: b2703ca1fb5f
Create Date: 2025-05-15 13:11:58.819652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3146cc95350'
down_revision: Union[str, None] = 'b2703ca1fb5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cpf_cnpj', sa.String(), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    op.add_column('users', sa.Column('telefone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'telefone')
    op.drop_column('users', 'email')
    op.drop_column('users', 'cpf_cnpj')
    # ### end Alembic commands ###
