"""initial migration

Revision ID: e19acd01d192
Revises: 
Create Date: 2025-05-15 15:11:19.197663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e19acd01d192'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cpf_cnpj', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf_cnpj')
    )
    op.create_table('documento_pessoal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credor_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('identidade', 'comprovante_residencia', 'etc', name='personaldocumentenum'), nullable=False),
    sa.Column('arquivo_url', sa.String(), nullable=True),
    sa.Column('enviado_em', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['credor_id'], ['credor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('precatorio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credor_id', sa.Integer(), nullable=False),
    sa.Column('numero_precatorio', sa.String(), nullable=False),
    sa.Column('valor_nominal', sa.Float(), nullable=False),
    sa.Column('foro', sa.String(), nullable=True),
    sa.Column('data_publicacao', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['credor_id'], ['credor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('precatorio')
    op.drop_table('documento_pessoal')
    op.drop_table('credor')
    # ### end Alembic commands ###
